# Generated by Django 2.0.3 on 2018-03-18 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_engine.UrlList')),
            ],
        ),
        migrations.CreateModel(
            name='WordLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_engine.UrlList')),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_engine.WordList')),
            ],
        ),
    ]
