# Generated by Django 2.0.3 on 2018-03-18 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_urllist_wordlist_wordlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.IntegerField()),
                ('to_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LinkWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_engine.Link')),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_engine.WordList')),
            ],
        ),
    ]
